#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Right1,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           Arm1,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           Claw,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Arm2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
 while (1 == 1)
 {
   //Don't assign more than one button to the same task, as one direction won't work very well
   motor[port2] = vexRT[Ch2]*5/6; //This makes the right wheel move forward and backward
   motor[port8] = vexRT[Ch3]*5/6;//This makes the left wheel move forward and backward



   motor[port3] = 80*vexRT[Btn7D]; //These four things move the arm, NEVER have them move at different rates
   motor[port9] = 80*vexRT[Btn7D];
   motor[port3] = -80*vexRT[Btn7U];
   motor[port9] = -80*vexRT[Btn7U];

if (vexRT[Btn5U] == 1){
   motor[port7] = vexRT[Ch4]/2; //Opens/Closes Claws
 }
 }
}
